//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCandidato { get; set; }
        public Nullable<int> IdVacante { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estatus { get; set; }
    }
}
