//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidato()
        {
            this.experienciaLaboral = new HashSet<experienciaLaboral>();
            this.candidatoVacante = new HashSet<candidatoVacante>();
            this.candidatoLicencia = new HashSet<candidatoLicencia>();
            this.candidatoTitulo = new HashSet<candidatoTitulo>();
            this.candidatoPrograma = new HashSet<candidatoPrograma>();
            this.configuracion = new HashSet<configuracion>();
            this.candidatoIdioma = new HashSet<candidatoIdioma>();
            this.preferenciaHorario = new HashSet<preferenciaHorario>();
            this.preferenciaPuesto = new HashSet<preferenciaPuesto>();
            this.preferenciaArea = new HashSet<preferenciaArea>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string CedulaIdentificacion { get; set; }
        public bool Pasaporte { get; set; }
        public bool Genero { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int EstadoCivil { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public bool Licencia { get; set; }
        public bool Vehiculo { get; set; }
        public int NivelComputo { get; set; }
        public string Referido { get; set; }
        public System.DateTime FechaCurriculum { get; set; }
        public bool EdoCurriculum { get; set; }
        public string Fotografia { get; set; }
        public string Perfil { get; set; }
        public Nullable<decimal> SalarioMinimo { get; set; }
        public Nullable<decimal> SalarioMaximo { get; set; }
        public Nullable<System.DateTime> FechaActualizacionCurriculum { get; set; }
        public string Apellido2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experienciaLaboral> experienciaLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatoVacante> candidatoVacante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatoLicencia> candidatoLicencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatoTitulo> candidatoTitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatoPrograma> candidatoPrograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<configuracion> configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatoIdioma> candidatoIdioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preferenciaHorario> preferenciaHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preferenciaPuesto> preferenciaPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preferenciaArea> preferenciaArea { get; set; }
    }
}
