//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidatoVacante
    {
        public int idCandidato { get; set; }
        public int idVacante { get; set; }
        public System.DateTime fechaAplicacion { get; set; }
        public int Id { get; set; }
        public string experienciaPuestoSimilar { get; set; }
        public string expectativaSalarial { get; set; }
        public string fechaPosibleIncorporacion { get; set; }
    
        public virtual candidato candidato { get; set; }
    }
}
