//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public int Id { get; set; }
        public int IdCandidato { get; set; }
        public bool VerReferencia { get; set; }
        public bool CorreoInformativo { get; set; }
        public bool EstadoCurriculum { get; set; }
        public bool VerPruebaPsicometrica { get; set; }
        public bool VerEntrevistaOnLine { get; set; }
        public bool VerPruebaCompetencia { get; set; }
        public bool VerPruebaIngles { get; set; }
    
        public virtual candidato candidato { get; set; }
    }
}
