//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosDePW
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool Genero { get; set; }
        public string EstadoCivil { get; set; }
        public string Escolaridad { get; set; }
        public string TituloProfesional { get; set; }
        public int AraeInteres { get; set; }
        public int SubArea { get; set; }
        public string CorreoElectronico { get; set; }
        public int Estado { get; set; }
        public int Pais { get; set; }
        public string Telefono { get; set; }
        public string CelularMovil { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
