//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresaVeCurriculum
    {
        public int idCandidato { get; set; }
        public int idEmpresa { get; set; }
        public int id { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
