//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.empresaVeCurriculum = new HashSet<empresaVeCurriculum>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreEmpresa { get; set; }
        public string Descripcion { get; set; }
        public int IdGiro { get; set; }
        public string TelefonoPrimario { get; set; }
        public string TelefonoSecundario { get; set; }
        public string Fax { get; set; }
        public string ProductoServicio { get; set; }
        public string NombreEncargado { get; set; }
        public string ApellidoEncargado { get; set; }
        public string Referido { get; set; }
        public string RazonSocial { get; set; }
        public string Rfc { get; set; }
        public string EmailEmpresa { get; set; }
        public string Paginaweb { get; set; }
        public int CantidadEmpleado { get; set; }
        public byte[] Logo { get; set; }
        public int IdPais { get; set; }
        public int IdEstado { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public int IdGeolocalizacion { get; set; }
    
        public virtual giroEmpresa giroEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresaVeCurriculum> empresaVeCurriculum { get; set; }
    }
}
