//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class experienciaLaboral
    {
        public int idExperienciaLaboral { get; set; }
        public string puestoDesempeniado { get; set; }
        public string nombreEmpresa { get; set; }
        public string telefonoEmpresa { get; set; }
        public string jefe { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public string funcion { get; set; }
        public string logro { get; set; }
        public string razonSalida { get; set; }
        public int idArea { get; set; }
        public int idGiro { get; set; }
        public int idCandidato { get; set; }
    
        public virtual area area { get; set; }
        public virtual candidato candidato { get; set; }
        public virtual giroEmpresa giroEmpresa { get; set; }
    }
}
