//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionPruebas
    {
        public int Id { get; set; }
        public int idCandidato { get; set; }
        public bool AplicadoPW { get; set; }
        public bool AplicadoLPC { get; set; }
        public bool AplicadoIngles { get; set; }
        public bool PruebasAplicadas { get; set; }
        public System.DateTime FechaNotificacion { get; set; }
        public bool Notificado { get; set; }
    }
}
