//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferencia
    {
        public Nullable<decimal> salarioDolar { get; set; }
        public bool dispuestoViajar { get; set; }
        public bool otraCiudad { get; set; }
        public bool otroPais { get; set; }
        public string habilidad { get; set; }
        public string comentario { get; set; }
        public int idCandidato { get; set; }
        public int idPreferencia { get; set; }
    }
}
