//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenciaPregunta
    {
        public int idReferencia { get; set; }
        public int idPregunta { get; set; }
        public string respuesta { get; set; }
        public int id { get; set; }
    
        public virtual pregunta pregunta { get; set; }
    }
}
