//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasIngles
    {
        public int Id { get; set; }
        public int IdPregunta { get; set; }
        public int IdAplicacion { get; set; }
        public int Respuesta { get; set; }
    
        public virtual AplicacionesIngles AplicacionesIngles { get; set; }
    }
}
