//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public int idEstado { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
        public string codigoPostal { get; set; }
        public int idUsuario { get; set; }
        public int idUbicacion { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
