//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacanteEducacion
    {
        public int idVacanteEducacion { get; set; }
        public int idVacanteNivelEducacion { get; set; }
        public int idVacanteStatusEducacion { get; set; }
    
        public virtual vacanteNivelEducacion vacanteNivelEducacion { get; set; }
        public virtual vacanteStatusEducacion vacanteStatusEducacion { get; set; }
    }
}
