//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacante
    {
        public int IdVacante { get; set; }
        public int IdUsuario { get; set; }
        public string Puesto { get; set; }
        public string DescripcionPuesto { get; set; }
        public string PalabrasClave { get; set; }
        public string DireccionDeTrabajo { get; set; }
        public bool MostrarDireccion { get; set; }
        public bool RecibirCVEnPanel { get; set; }
        public int IdArea { get; set; }
        public int IdSubArea { get; set; }
        public int IdPais { get; set; }
        public int IdEstado { get; set; }
        public string ReqExperienciaMinima { get; set; }
        public string ReqEdadMinima { get; set; }
        public string ReqEdadMaxima { get; set; }
        public int ReqTipoEdad { get; set; }
        public int ReqGenero { get; set; }
        public decimal ReqSalarioMinimo { get; set; }
        public decimal ReqSalarioMaximo { get; set; }
        public int ReqSalarioTipoPago { get; set; }
        public int ReqSalarioFormaPago { get; set; }
        public bool ReqMostrarEnAviso { get; set; }
        public bool ReqSolicitarSalarioPostulante { get; set; }
        public string ReqTecnologia { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public Nullable<System.DateTime> FechaFinPublicacion { get; set; }
        public bool NotRecibirTodo { get; set; }
        public bool NotRecibirResumen { get; set; }
        public bool NotPrimerPostulante { get; set; }
        public bool NotDesactivarNotificaciones { get; set; }
        public int TipoPuesto { get; set; }
        public int IdIdioma { get; set; }
        public int IdNivelIdioma { get; set; }
        public int IdEducacion { get; set; }
        public int IdEstatusEducacion { get; set; }
        public bool Activa { get; set; }
        public int Vistas { get; set; }
        public int Actividad { get; set; }
        public int IdGeolocalizacion { get; set; }
    }
}
